### ISSUE TITLE
configure: error: invalid value of canonical build

### ISSUE THREAD

**Issue by syedkhizarulhaq-cis** [LibtraceTeam/libtrace#113]
Hi,

I was trying to install the libflowmanager library but after running the ./configure with path to the libtrace library i.e ./configure ../../../../usr/local/lib, Im getting the error configure: **error: invalid value of canonical build**. 
![Screenshot from 2019-07-03 15-09-50](https://user-images.githubusercontent.com/33244888/60583583-a16d4100-9da4-11e9-866e-61bd48cf3066.png)

**Comment by salcock** [comment]
Hello,

This is not the correct way to tell `configure` the location of an installed library. You need to use `LDFLAGS` to do this. You'll probably also want to set `CPPFLAGS` as well so that `configure` can also find the header files for libtrace.

So you want to run something like:

    ./configure LDFLAGS="-L/usr/local/lib/" CPPFLAGS="-I/usr/local/include"

Note the `-I` and `-L` flags in the line above -- don't forget these!

One final tip: if you've installed libtrace into its default location (`/usr/local/lib`) then you should be able to run:

    sudo ldconfig

and then other programs may be able to find it automatically without needing to set `LDFLAGS` when running `configure`.

**Comment by syedkhizarulhaq-cis** [comment]
Hi,
Thanks for the help. I had the libtrace library not properly installed.

Now its working.

Thanks.
