### ISSUE TITLE
trace linktype <-> pcap_dlt conversion api is not available

### ISSUE THREAD

**Issue by EaseTheWorld** [LibtraceTeam/libtrace#119]
My capture module is libtrace() but I want to pass the libtrace linktype to other module
which doesn't understand libtrace type.

Any reason not to expose libtrace_to_pcap_dlt()?

**Comment by EaseTheWorld** [comment]
I tried to commit myself to expose some apis but
Which is inverse of pcap_linktype_to_libtrace(),
libtrace_to_pcap_dlt? or libtrae_to_pcap_linktype?
There seems a history about RAW type, which doesn't have 1:1 mapping.

**Comment by salcock** [comment]
libtrace_to_pcap_linktype() is probably your best bet to reverse pcap_linktype_to_libtrace.

Unfortunately (as you are discovering) linktypes are pretty annoying to have to deal with, which is why we try to hide this stuff from users as much as possible. Things will get even more complicated when you have to consider that certain DLTs have different values on some BSD systems.

I'm not strongly opposed to exposing at least libtrace_to_pcap_dlt() if there is a good use case for doing so, but I imagine those cases are pretty obscure and rare.

**Comment by EaseTheWorld** [comment]
OK. that's why.

I will choose workaround like
  if (linktype==TRACE_TYPE_NONE)
    datalink_for_other_api = TRACE_DLT_RAW;
  else
    datalink_for_other_api = TRACE_DLT_EN10MB;
