### ISSUE TITLE
trace_create: Unknown format (dag)

### ISSUE THREAD

**Issue by maganiss** [LibtraceTeam/libtrace#143]
Hi there,
After installing Libtrace, now I want to use tracepktdump to see my DAG file content using the following command:
`tracepktdump -f "tcp port 80" dag:20040709-093005-0.tsa`
But I get the following error:
`trace_create: Unknown format (dag)`

I haven't installed Libtrace using --with-dag since I've only downloaded the trace and I don't have DAG card on my own machine. However, just to see what happens, I tried `./configure --with-dag=COSTUM_DIR` and it returned this error: `configure: error: DAG API not found under directory CUSTOM_DIR`

Could you please help me with this? How can I use libtrace to see a DAG trace content?

**Comment by salcock** [comment]
Hello,

Files captured using a DAG card can be read using the ERF format in libtrace, e.g.
```
tracepktdump -f "tcp port 0" erf:20040709-093005-0.tsa
```

Does that help?

**Comment by maganiss** [comment]
Yes, thanks!

**Comment by salcock** [comment]
ERF (or Extensible Record Format) is the native format for trace files produced by DAG cards (see https://www.endace.com/erf-extensible-record-format-types.pdf, page 3). Any trace file captured by a DAG card using its native format should technically be described as an ERF trace, rather than saying it is in "DAG format".

In libtrace, we can also read packets directly from a DAG card in real-time -- we use `dag:` for these situations.

We use `erf:` for files that are written using the ERF format (either by DAG software, or by converting another format such as pcap into ERF using a tool like `traceconvert`). 

More details on the different formats supported by libtrace can be found at https://github.com/LibtraceTeam/libtrace/wiki/Supported-Trace-Formats
