### ISSUE TITLE
Libtrace version libtrace.so.7

### ISSUE THREAD

**Issue by idasiahaan** [LibtraceTeam/libtrace#183]
Hi,
I cloned libtrace from git then I followed the instruction. However, the created library is not libtrace.so.4
libtrace.so -> libtrace.so.7.0.0
libtrace.so.7 -> libtrace.so.7.0.0
libtrace.so.7.0.0

When I add symbolic link 
$ sudo ln -s libtrace.so.7.0.0 libtrace.so.4 

Then I run 
$ sudo ldconfig
The result is still  libtrace.so.7
/usr/local/lib:
...        libtrace.so.7 -> libtrace.so.7.0.0

The problem is that when I install corsaro and try running e.g. corsarotagger, then it will give the following error:
corsarotagger: error while loading shared libraries: libtrace.so.4: cannot open shared object file: No such file or directory

I am using Ubuntu 18.04

Could you please let me know how to solve this ?

Thank you.

**Comment by salcock** [comment]
Hi,

You have a couple of possible options here.

One would be to downgrade to an earlier libtrace release, e.g.
```
git checkout 4.0.15-1
```
and then rebuild and install libtrace from that branch. You may want to remove `/usr/local/lib/libtrace.so.*` beforehand, just to make sure that the previous version does not interfere.

The other option would be to instead build the corsaro code from source rather than using the packaged version, which will force `corsarotagger` to link against the .7 version of the .so.

In the meantime, I will try to arrange a rebuild of the corsaro packages so the most recent packaged binaries are not linked against the older .4 version of libtrace.

**Comment by salcock** [comment]
There should now be a new version of the corsaro packages available that will work with the latest version of libtrace:

```
sudo apt update && sudo apt install corsaro3-tools
```

should upgrade to the latest package version for you.

**Comment by idasiahaan** [comment]
Thank you very much. Now the updated corsaro packages works with the latest version of libtrace .
