### ISSUE TITLE
Recommend a stable version of libtrace

### ISSUE THREAD

**Issue by Crazycuo** [LibtraceTeam/libtrace#214]
Hi,

we are trying to use libtrace for our project. Our project nees to be very stable. So, could you please recommend a stable version of libtrace?

Regards,

**Comment by salcock** [comment]
Generally speaking, you could probably pick any libtrace release from the last 2-3 years and that would work just fine. Most code changes these days are adding support for new, often niche, capture formats or protocol decoding features, or fixing very rare bugs.

This is especially the case if you intend to use capture methods that we have supported for a long time (such as pcap, ERF, ring). This code is very mature and is unlikely to change at all.

DPDK is a bit more complicated, but mainly that is because the underlying DPDK library often undergoes significant API changes and we need to update libtrace accordingly (i.e. to replace calls to deprecated functions with their new alternatives, or handle situations where formerly public structure members are now private). But as long as you stick to the same stable DPDK and then choose a version of libtrace that works with that particular version, then DPDK changes shouldn't be an issue.
