### ISSUE TITLE
how to read compressed pcaps with libtrace 

### ISSUE THREAD

**Issue by rogersce** [LibtraceTeam/libtrace#71]
Hi,

This may be a duplicate of https://github.com/LibtraceTeam/libtrace/issues/14, but for gzipped files.

I have a set of pcaps I'd like to parse and analyze with some custom code. Everything works fine when the pcaps are uncompressed. When I compress them (via gzip my.pcap) and re-run, libtrace errors out with the following message:

```
Error: RT type 20 cannot be converted to a pcap DLT
Assertion failed: (false), function rt_to_pcap_linktype, file linktypes.c, line 162.
./analysis.sh: line 5:  6042 Abort trap: 6           ./analysis "$FNAME"
```

Am I doing something wrong trying to run a gzipped file through the same code as an uncompressed file, or does libtrace not support reading in compressed pcaps? If it's the latter, I could possibly work on a PR to enable this option, but want to confirm it's not user error (me) first :)

Here's how I'm opening the file, it's pretty basic:
```
libtrace_t* file = trace_create(fpath.c_str());
libtrace_packet_t* packet = trace_create_packet();
libtrace_filter_t* bpf = trace_create_filter(bpf_s.c_str()); //bpf = udp

if(!file) throw std::runtime_error("Problem in trace create");
if(trace_config(file, TRACE_OPTION_FILTER, bpf) == -1) throw std::runtime_error("Problem in trace config");
if(trace_start(file) < 0) throw std::runtime_error("Problem in trace_start");
```

**Comment by salcock** [comment]
Hi,

The problem here is actually that you are trying to apply a BPF filter to a PCAP NG trace, which currently doesn't work properly in libtrace. I'm hoping to get around to fixing this once I get some spare time.

For now, you can get around this by converting your PCAP NG trace to a traditional pcap trace using

``tracesplit -z 1 origtrace.pcap.gz pcapfile:fixedtrace.pcap.gz``

Your libtrace program should work as expected if you give it the "fixed" trace as input. 

PS. Increase the number after the ``-z`` if you want to use a higher compression level.

**Comment by rogersce** [comment]
It worked, thank you for the help!
